chore: migrate code formatter to dprint - migrate config schemas to top of file directives - reformat files - update workspace settings

diff --git a/Taskfile.yml b/Taskfile.yml
--- a/Taskfile.yml
+++ b/Taskfile.yml
@@ -1,10 +1,43 @@
 version: "3"
 env:
+  REPO_ROOT:
+    sh: |
+      echo {{ osClean "$(git rev-parse --show-toplevel)" }}
+
+  # enable sccache for all tasks, if available
+  RUSTC_WRAPPER:
+    sh: |
+      sccache="{{ fromSlash "$HOME/.cargo/bin/sccache" }}{{if eq OS "windows"}}.exe{{end}}"
+      if [ -z $(command -v $sccache) ]; then
+        echo "";
+      else
+        echo "$sccache";
+      fi
+  # scoped sccache dir
+  SCCACHE_DIR:
+    sh: |
+      cd {{ .REPO_ROOT }} ;
+      sh -c "mkdir -p ./.sccache" ;
+      cd ./.sccache ;
+      echo {{ osClean "$(pwd)" }}
+
+  # fast build with only host CPU optimizations
   RUSTFLAGS: -C target-cpu=native -Copt-level=0
-  DENO_DIR: ./.deno
+  DENO_DIR:
+    sh: |
+      cd {{ .REPO_ROOT }} ;
+      sh -c "mkdir -p ./.deno" ;
+      cd ./.deno ;
+      echo {{ osClean "$(pwd)" }}
+  # scoped deno cache dir
+  DPRINT_CACHE_DIR:
+    sh: |
+      cd {{ .REPO_ROOT }} ;
+      sh -c "mkdir -p ./.dprint" ;
+      cd ./.dprint ;
+      echo {{ osClean "$(pwd)" }}
 
 tasks:
-  ##### Tauri Build Hooks #####
   ui:dev:
     desc: Run Vite front-end dev server with Deno
     summary: |
@@ -28,13 +61,14 @@ tasks:
     summary: |
       - Download latest versions of Memos server binaries to `server-dist/`
     cmds:
-      - deno run -A ./src-tauri/scripts/before_build.ts
+      - deno run -A ./build-scripts/downloadMemosBuildsHook.ts
     status:
       - test -f ./server-dist/memos-x86_64-unknown-linux-gnu
       - test -f ./server-dist/memos-x86_64-pc-windows-msvc.exe
       - test -f ./server-dist/memos-x86_64-apple-darwin
       - test -f ./server-dist/memos-aarch64-apple-darwin
 
+  ##### Tauri Build Hooks #####
   tauri:hook:before-dev:
     desc: Before dev scripts
     cmds:
@@ -56,7 +90,7 @@ tasks:
     summary: |
       - upx
     cmds:
-      - deno run -A ./src-tauri/scripts/before_bundle.ts
+      - deno run -A ./build-scripts/upxPackHook.ts
   ##### /Build Hooks #####
 
   ##### Development #####
@@ -66,32 +100,27 @@ tasks:
       - This will start the app in development mode.
       - It will automatically reload the app when you make changes.
       - A fast Rust build is prioritized.
-
     deps:
-      - task: dev:posix
-      - task: dev:windows
-  dev:posix:
+      - task: dev:killprocesses
+    cmds:
+      - cargo tauri dev
+      - task: dev:killprocesses
+      - task: sccache:stats
+  dev:killprocesses:
+    desc: Kill all running Memospot/Memos processes
+    cmds:
+      - task: dev:killprocesses:posix
+      - task: dev:killprocesses:windows
+  dev:killprocesses:posix:
     platforms: [linux, darwin]
     internal: true
-    env:
-      RUSTC_WRAPPER:
-        sh: echo "$HOME/.cargo/bin/sccache"
     cmds:
       - killall memospot || true
       - killall memos || true
-      - cargo tauri dev
-      - killall memospot || true
-      - killall memos || true
-  dev:windows:
+  dev:killprocesses:windows:
     platforms: [windows]
     internal: true
-    env:
-      RUSTC_WRAPPER:
-        sh: echo "$HOME\.cargo\bin\sccache.exe"
     cmds:
-      - taskkill /f /t /im memospot.exe || true
-      - taskkill /f /t /im memos.exe || true
-      - cargo tauri dev
       - taskkill /f /t /im memospot.exe || true
       - taskkill /f /t /im memos.exe || true
 
@@ -99,8 +128,6 @@ tasks:
     desc: Update project dependencies
     cmds:
       - cd ./src-tauri; cargo update
-      - pnpm update
-      - pnpm update @tauri-apps/cli @tauri-apps/api --latest
 
   update-toolchain:
     desc: Update project toolchain
@@ -108,7 +135,6 @@ tasks:
       - rustup update
       - rustup self update
       - rustup component add clippy
-      - pnpm add -g pnpm
 
   gen:icons:
     desc: Generate app icons from `assets/app-icon-lossless.webp`
@@ -126,11 +152,11 @@ tasks:
     summary: |
       - This will create an universal x86-64 optimized build of the app.
     env:
+      # optimized universal x86-64 build
       RUSTFLAGS: -Ctarget-cpu=x86-64 -Copt-level=3 -Cstrip=symbols -Ccodegen-units=1
-      RUSTC_WRAPPER:
-        sh: echo "{{if eq OS "windows"}}$HOME\.cargo\bin\sccache.exe{{else}}$HOME/.cargo/bin/sccache{{end}}"
     cmds:
       - cargo tauri build
+      - sccache --show-stats || true
       - task: postbuild
 
   postbuild:
@@ -147,23 +173,26 @@ tasks:
 
   ##### Clean #####
   clean:
-    desc: Cleanup ALL build artifacts, node modules and downloaded memos binaries.
+    desc: Cleanup ALL build artifacts, deno/node modules and downloaded memos binaries.
     summary: |
-      This will free up nearly 10GB of disk space, but will require a full rebuild.
+      This will free up nearly 20GB of disk space, but will require a full rebuild.
       Don't use unless you know what you're doing.
     deps:
       - clean:posix
       - clean:windows
     ignore_error: true
     cmds:
-      - sh -c "rm -rf ./src-tauri/target"
-      - sh -c "rm -rf ./src-ui/.deno"
-      - sh -c "rm -rf ./src-ui/.vite"
+      - sh -c "rm -rf ./.deno"
+      - sh -c "rm -rf ./.dprint"
+      - sh -c "rm -rf ./.sccache"
+      - sh -c "rm -rf ./.task"
       - sh -c "rm -rf ./build"
       - sh -c "rm -rf ./dist-ui"
-      - sh -c "rm -rf ./server-dist"
-      - sh -c "rm -rf ./.deno"
       - sh -c "rm -rf ./.node_modules"
+      - sh -c "rm -rf ./server-dist"
+      - sh -c "rm -rf ./src-tauri/target"
+      - sh -c "rm -rf ./src-ui/.vite"
+
   clean:posix:
     platforms: [linux, darwin]
     internal: true
@@ -180,49 +209,80 @@ tasks:
       - taskkill /f /t /im memos.exe || true
   ##### /Clean #####
 
+  ##### Miscellanea #####
+  sccache:clear:
+    desc: Clear sccache cache
+    cmds:
+      - sccache --show-stats || true
+      - sccache --stop-server || true
+      - sccache --zero-stats || true
+      - sccache --start-server || true
+      - sccache --show-stats || true
+  sccache:stats:
+    desc: Show sccache stats
+    silent: true
+    cmds:
+      - |
+        if ! [ -z {{.RUSTC_WRAPPER}} ]; then
+          export RUSTC_WRAPPER={{.RUSTC_WRAPPER}};
+          sccache --show-stats
+          exit 0
+        fi
+        echo "sccache not available"
+
   ##### Code Lint #####
   lint:
     aliases:
       - check
     desc: Run all checkers/linters in parallel
     deps:
-      - lint:backend
-      - lint:config
-      - lint:frontend
-  lint:backend:
-    desc: lint backend
-    cmds:
-      - cd ./src-tauri; cargo fmt --all --check
-      - cd ./src-tauri; cargo clippy --all-features --workspace --locked
-      - cd ./src-tauri/scripts; pnpm eslint --ext .ts,.tsx,.mts,.cts
-  lint:config:
-    desc: lint config
+      - lint:cargo
+      - lint:deno
+      - lint:taplo
+      - lint:dprint
+  lint:cargo:
+    desc: lint rust with cargo clippy
     dir: ./src-tauri
     cmds:
-      - taplo lint Tauri.toml --schema=https://raw.githubusercontent.com/tauri-apps/tauri/tauri-cli-v1.5.6/core/tauri-config-schema/schema.json
-      - taplo lint Cargo.toml --schema=https://json.schemastore.org/cargo.json
-      - taplo lint .rustfmt.toml --schema=https://json.schemastore.org/rustfmt.json
-  lint:frontend:
-    desc: lint frontend
+      - cargo fmt --all --check
+      - cargo clippy --all-features --workspace --locked
+      - task: sccache:stats
+    method: checksum
+    sources:
+      - ./src/**/*.rs
+      - build.rs
+      - Cargo.toml
+      - Tauri.toml
+      - .rustfmt.toml
+  lint:deno:
+    desc: lint typescript with deno
     cmds:
-      - cd ./src; pnpm eslint --ext .js,.jsx,.mjs,.cjs,.ts,.tsx,.mts,.cts
+      - cd ./src-ui; deno lint
+      - cd ./build-scripts; deno lint
+  lint:taplo:
+    desc: lint config (also check schemas)
+    dir: ./src-tauri
+    cmds:
+      - taplo lint Tauri.toml
+      - taplo lint Cargo.toml
+      - taplo lint .rustfmt.toml
+  lint:dprint:
+    desc: lint with dprint
+    cmds:
+      - cd ./src-ui; dprint check
+      - cd ./build-scripts; dprint check
   ##### /Code Lint #####
 
   ##### Code Fix #####
   fix:
     desc: Run all fixers in parallel
     deps:
-      - fix:backend
-      - fix:frontend
-  fix:backend:
-    desc: fix backend
+      - fix:cargo
+  fix:cargo:
+    desc: Run cargo fix
     cmds:
       - cd ./src-tauri; cargo fix
-      - cd ./src-tauri/scripts; pnpm eslint --ext .ts,.tsx,.mts,.cts --fix
-  fix:frontend:
-    desc: fix frontend
-    cmds:
-      - cd ./src; pnpm eslint --ext .js,.jsx,.mjs,.cjs,.ts,.tsx,.mts,.cts --fix
+
   ##### /Code Fix #####
 
   ##### Code Format #####
@@ -231,26 +291,18 @@ tasks:
     aliases:
       - fmt
     deps:
-      - format:backend
-      - format:config
-      - format:frontend
-  format:backend:
-    desc: format backend
+      - format:cargo
+      - format:dprint
+  format:cargo:
+    desc: Format with cargo fmt
     cmds:
       - cd ./src-tauri; cargo fmt --all
-      - pnpm prettier ./src-tauri/scripts --write --ignore-path .gitignore --ignore-path .prettierignore
-  format:config:
-    desc: format config
-    ignore_error: true
+  format:dprint:
+    desc: Format with dprint
     cmds:
-      - taplo format ./src-tauri/.rustfmt.toml
-      - taplo format .taplo.toml
-      - taplo format ./src-tauri/Cargo.toml
-      - taplo format ./src-tauri/Tauri.toml
-  format:frontend:
-    desc: format frontend
-    cmds:
-      - pnpm prettier ./src --write --ignore-path .gitignore --ignore-path .prettierignore
+      - cd ./src-tauri; dprint fmt
+      - cd ./src-ui; dprint fmt
+      - cd ./build-scripts; dprint fmt
 
   ##### /Code Format #####
 
@@ -272,7 +324,7 @@ tasks:
     interactive: true
     cmds:
       - |
-        sudo apt update &&
+        sudo apt update -y &&
         sudo apt install -y \
           build-essential \
           curl \
@@ -287,97 +339,145 @@ tasks:
         sudo apt install -y libappindicator3-dev || true
         echo -e '\e[33mNOTE: "libayatana-appindicator3-1" may conflict with libappindicator3-dev, its ok to ignore.\e[0m'
 
-  setup:node:
-    desc: "Setup node"
-    deps:
-      - setup:node:posix
-      - setup:node:windows
-  setup:node:posix:
+  setup:deno:
+    desc: "Setup Deno"
+    cmds:
+      - task: setup:deno:posix
+      - task: setup:deno:windows
+    status:
+      - sh -c 'if [ -z $(command -v deno) ]; then exit 1; fi'
+  setup:deno:posix:
     platforms: [darwin, linux]
     internal: true
+    silent: true
     cmds:
-      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
-      - export NVM_DIR="$HOME/.nvm"; [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"; nvm install 18; nvm use 18
-    status:
-      - test -f "$HOME/.nvm/nvm.sh"
-      - 'if ! [ "`$`(command -v nvm)" ]; then exit 1; fi'
-  setup:node:windows:
+      - |
+        if ! [ -z $(command -v brew) ]; then
+          brew install deno
+          exit 0
+        fi
+        echo -e '\e[33mERROR: Homebrew not found. Please install Deno manually.
+
+        Alternatively, install Homebrew and run this task again.\e[0m'
+
+        echo -e '\e[34m
+        https://deno.com
+        https://brew.sh
+        \e[0m'
+  setup:deno:windows:
     platforms: [windows]
     internal: true
+    silent: true
     cmds:
-      - powershell.exe -NoProfile -ExecutionPolicy Bypass -Command "Invoke-WebRequest -OutFile '$TEMP\nvm-setup.exe' -Uri 'https://github.com/coreybutler/nvm-windows/releases/latest/download/nvm-setup.exe' -UseBasicParsing; Start-Process -Wait '$TEMP\nvm-setup.exe' /silent ; Remove-Item -Path '$TEMP\nvm-setup.exe' -Force;"
-      - export PATH="$PATH;$HOME\.nvm"; nvm install 18; nvm use 18
-    status:
-      - sh -c 'test -f "$HOME/.nvm/nvm.exe"'
+      - |
+        if ! [ -z $(command -v choco) ]; then
+          echo "Installing Deno via Chocolatey..."
+          powershell -Command 'Start-Process -Wait -Verb RunAs -FilePath "choco" -ArgumentList "install deno -y"'
+          exit 0
+        fi
+        if ! [ -z $(command -v winget) ]; then
+          echo "Installing Deno via Winget..."
+          winget install --id Denoland.deno
+          exit 0
+        fi
+        if ! [ -z $(command -v scoop) ]; then
+          echo "Installing Deno via Scoop..."
+          scoop install deno
+          exit 0
+        fi
+        echo -e '\e[33mERROR: No package manager found. Please install Deno manually.
+
+        Alternatively, install Chocolatey, Winget or Scoop and run this task again.\e[0m'
+
+        echo -e '\e[34m
+        https://deno.com
+        https://chocolatey.org/install
+        https://apps.microsoft.com/detail/9NBLGGH4NNS1
+        https://scoop.sh/
+        \e[0m'
 
   setup:rust:
     desc: "Setup rust"
-    deps:
+    cmds:
       - setup:rust:posix
       - setup:rust:windows
+      - rustup default stable
+    status:
+      - sh -c 'if [ -z $(command -v rustup) ]; then exit 1; fi'
+      - sh -c 'if [ -z $(command -v rustc) ]; then exit 1; fi'
   setup:rust:posix:
     platforms: [darwin, linux]
     internal: true
+    silent: true
     cmds:
-      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
-      - source "$HOME/.cargo/env"; rustup default stable
-    status:
-      - test -f "$HOME/.cargo/bin/rustc"
+      - |
+        if ! [ -z $(command -v brew) ]; then
+          brew install rustup-init
+          rustup-init -y
+          source "$HOME/.cargo/env"; rustup default stable
+          exit 0
+        fi
+        echo -e '\e[34mHomebrew not found. Falling back to official install script.\e[0m'
+        nohup curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+        source "$HOME/.cargo/env"; rustup default stable
+        \e[0m'
   setup:rust:windows:
     platforms: [windows]
     internal: true
+    silent: true
     cmds:
-      - winget install --id Rustlang.Rustup
-      - export "PATH=$PATH;$HOME\.cargo\bin"; rustup default stable-msvc
-    status:
-      - sh -c 'test -f "$HOME/.cargo/bin/rustc.exe"'
+      - |
+        if ! [ -z $(command -v choco) ]; then
+          echo "Installing Rustup via Chocolatey..."
+          powershell -Command 'Start-Process -Wait -Verb RunAs -FilePath "choco" -ArgumentList "install rustup.install -y"'
+          exit 0
+        fi
+        if ! [ -z $(command -v winget) ]; then
+          echo "Installing Rustup via Winget..."
+          winget install --id Rustlang.Rustup
+          exit 0
+        fi
+        if ! [ -z $(command -v scoop) ]; then
+          echo "Installing Rustup via Scoop..."
+          scoop install rustup
+          exit 0
+        fi
+        echo -e '\e[33mERROR: No package manager found. Please install Rustup manually.
+
+        Alternatively, install Chocolatey, Winget or Scoop and run this task again.\e[0m'
+
+        echo -e '\e[34m
+        https://rustup.rs
+
+        https://chocolatey.org/install
+        https://apps.microsoft.com/detail/9NBLGGH4NNS1
+        https://scoop.sh/
+        \e[0m'
 
   setup:
     desc: Setup the project tooling.
     env:
+      # slow build with all optimizations
       RUSTFLAGS: -Ctarget-cpu=native -Copt-level=3 -Cstrip=symbols -Ccodegen-units=1
     deps:
       - setup:platformdeps
-      - setup:node
+      - setup:deno
       - setup:rust
     cmds:
-      - task: setup:posix
-      - task: setup:windows
-
-  setup:posix:
-    platforms: [darwin, linux]
-    internal: true
-    cmds:
-      - echo -e '\e[33mRun "nvm use 18" and repeat this task if you get an error about npm/pnpm not being found.\e[0m'
       - |
-        (. "$HOME/.nvm/nvm.sh" && nvm use 18) || (export PATH="$PATH:$HOME/.nvm/versions/node/v18.18.2/bin/");
-        npm install -g pnpm || true;
-        pnpm i --frozen-lockfile
-      - |
-        . "$HOME/.cargo/env";
-        rustup component add clippy;
-        cargo install tauri-cli --locked;
-        cargo install taplo-cli --locked;
-        cargo install cargo-edit --locked
-        cargo install sccache --locked
-
-  setup:windows:
-    platforms: [windows]
-    internal: true
-    cmds:
-      - |
-        export PATH="$PATH;$HOME\.nvm\current";
-        nvm use 18;
-        npm install -g pnpm || true;
-        pnpm i --frozen-lockfile
-      - |
+        {{if eq OS "windows"}}
         export PATH="$PATH;$HOME\.cargo\bin";
+        {{else}}
+        . "$HOME/.cargo/env";
+        {{end}}
         rustup component add clippy;
         cargo install tauri-cli --locked;
         cargo install taplo-cli --locked;
-        cargo install cargo-edit --locked
-        cargo install sccache --locked
-
+        cargo install cargo-edit --locked;
+        cargo install dprint --locked;
+        export RUSTC_WRAPPER="";
+        cargo install sccache --locked;
+  ##### /Developer Environment Setup #####
   ### Git Actions ###
   prepush:
     desc: Run all checks before pushing changes
